/**
 * Materialize the two session-mode agent presets into the user preset root
 * (`<dshHome>/.agent-presets/`). Preset discovery re-scans on every roster
 * read, so freshly written presets appear without a restart. Files carry a
 * generated-by marker; a file without the marker is user-owned and left alone.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { dshHomePath } from '@deepseek-ai/dsh-home-paths'

const MARKER = '# generated by dsh-roleplay — edits are overwritten on plugin start'

const ROLEPLAY_COMPOSITION = `${MARKER}
#
# Role-play session mode: an immersive story-acting agent. No coding tools;
# the persona, character context and illustration tool come from the
# dsh-roleplay session plugin below (it consumes the host-plane \`roleplay\`
# service registered by the dsh-roleplay bundle).

- id: roleplay-session
  name: 'dsh-roleplay/agent'
  config:
    mode: roleplay

# Native question tool: choice mode asks the user to pick the next action
# through the built-in ask_user_question card (the \`userQuestions\` service
# lives in the host composition's base layer).
- id: tool-ask-user
  name: '@deepseek-ai/dsh-tool-ask-user'
`

const ROLEPLAY_META = `${MARKER}
name: 角色扮演
description: 与角色卡进行沉浸式角色扮演对话，支持场景插图生成。
order: 20
`

const FORGE_COMPOSITION = `${MARKER}
#
# Character-forge session mode: the agent interviews the user, then writes
# and saves complete character cards through typed tools.

- id: forge-session
  name: 'dsh-roleplay/agent'
  config:
    mode: forge

# Native question tool, for clarifying questions with clickable options.
- id: tool-ask-user
  name: '@deepseek-ai/dsh-tool-ask-user'
`

const FORGE_META = `${MARKER}
name: 角色卡创作
description: 从一句灵感生成完整角色卡：人设、开场白、世界书与头像，可导出 PNG/JSON。
order: 21
`

async function writeManaged(path: string, content: string): Promise<void> {
  try {
    const existing = await readFile(path, 'utf8')
    if (!existing.startsWith(MARKER)) return
    if (existing === content) return
  } catch {
    // absent — write fresh
  }
  await writeFile(path, content, 'utf8')
}

/** Write (or refresh) the preset directories. */
export async function materializePresets(): Promise<void> {
  const root = dshHomePath('.agent-presets')
  const roleplayDir = join(root, 'roleplay')
  const forgeDir = join(root, 'character-forge')
  await mkdir(roleplayDir, { recursive: true })
  await mkdir(forgeDir, { recursive: true })
  await writeManaged(join(roleplayDir, 'agent.cordis.yml'), ROLEPLAY_COMPOSITION)
  await writeManaged(join(roleplayDir, 'preset.yml'), ROLEPLAY_META)
  await writeManaged(join(forgeDir, 'agent.cordis.yml'), FORGE_COMPOSITION)
  await writeManaged(join(forgeDir, 'preset.yml'), FORGE_META)
}
