/**
 * Materialize the two session-mode agent presets into the user preset root
 * (`<dshHome>/.agent-presets/`). Preset discovery re-scans on every roster
 * read, so freshly written presets appear without a restart. Files carry a
 * generated-by marker; a file without the marker is user-owned and left alone.
 *
 * The preset.yml metadata format is plain strings — no locale map — so the
 * display text is written in the UI language the host currently has
 * configured, and rewritten when that setting changes (see src/index.ts).
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { dshHomePath } from '@deepseek-ai/dsh-home-paths'

/** UI languages the display metadata ships in; mirrors the dsh locale ids. */
export type PresetLocale = 'zh' | 'en'

const MARKER = '# generated by dsh-roleplay — edits are overwritten on plugin start'

const ROLEPLAY_COMPOSITION = `${MARKER}
#
# Role-play session mode: an immersive story-acting agent. No coding tools;
# the persona, character context and illustration tool come from the
# dsh-roleplay session plugin below (it consumes the host-plane \`roleplay\`
# service registered by the dsh-roleplay bundle).

- id: roleplay-session
  name: 'dsh-roleplay/agent'
  config:
    mode: roleplay

# Native question tool: choice mode asks the user to pick the next action
# through the built-in ask_user_question card (the \`userQuestions\` service
# lives in the host composition's base layer).
- id: tool-ask-user
  name: '@deepseek-ai/dsh-tool-ask-user'
`

const ROLEPLAY_META: Record<PresetLocale, string> = {
  zh: `${MARKER}
name: 角色扮演
description: 与角色卡进行沉浸式角色扮演对话，支持场景插图生成。
order: 20
`,
  en: `${MARKER}
name: Role-play
description: Immersive role-play conversations with character cards, with scene illustration generation.
order: 20
`,
}

const FORGE_COMPOSITION = `${MARKER}
#
# Character-forge session mode: the agent interviews the user, then writes
# and saves complete character cards through typed tools.

- id: forge-session
  name: 'dsh-roleplay/agent'
  config:
    mode: forge

# Native question tool, for clarifying questions with clickable options.
- id: tool-ask-user
  name: '@deepseek-ai/dsh-tool-ask-user'
`

const FORGE_META: Record<PresetLocale, string> = {
  zh: `${MARKER}
name: 角色卡创作
description: 从一句灵感生成完整角色卡：人设、开场白、世界书与头像，可导出 PNG/JSON。
order: 21
`,
  en: `${MARKER}
name: Character Forge
description: 'Turn one line of inspiration into a complete character card: persona, greeting, lorebook and avatar, exportable as PNG/JSON.'
order: 21
`,
}

/** @returns whether the file was (re)written. */
async function writeManaged(path: string, content: string): Promise<boolean> {
  try {
    const existing = await readFile(path, 'utf8')
    if (!existing.startsWith(MARKER)) return false
    if (existing === content) return false
  } catch {
    // absent — write fresh
  }
  await writeFile(path, content, 'utf8')
  return true
}

/**
 * Write (or refresh) the preset directories in the given display language.
 * @returns whether any file changed — the caller's cue to tell connected
 * clients their cached preset roster is stale.
 */
export async function materializePresets(locale: PresetLocale = 'zh'): Promise<boolean> {
  const root = dshHomePath('.agent-presets')
  const roleplayDir = join(root, 'roleplay')
  const forgeDir = join(root, 'character-forge')
  await mkdir(roleplayDir, { recursive: true })
  await mkdir(forgeDir, { recursive: true })
  const writes = [
    await writeManaged(join(roleplayDir, 'agent.cordis.yml'), ROLEPLAY_COMPOSITION),
    await writeManaged(join(roleplayDir, 'preset.yml'), ROLEPLAY_META[locale]),
    await writeManaged(join(forgeDir, 'agent.cordis.yml'), FORGE_COMPOSITION),
    await writeManaged(join(forgeDir, 'preset.yml'), FORGE_META[locale]),
  ]
  return writes.some(Boolean)
}
